### ISSUE TITLE
ValueError: Expecting , delimiter

### ISSUE THREAD

**Issue by idleberg** [gt3389b/python-cson#3]
I've been trying to convert Atom snippets (CSON format) to JSON, but no matter which file I'm using as input, I always end up with the same error.

``` bash
$ python-cson -f fa.json fa.cson
Traceback (most recent call last):
  File "/usr/local/bin/python-cson", line 8, in <module>
    load_entry_point('python-cson==1.0.9', 'console_scripts', 'python-cson')()
  File "/Library/Python/2.7/site-packages/python_cson-1.0.9-py2.7.egg/cson.py", line 335, in main
    data = load(args.input_file)
  File "/Library/Python/2.7/site-packages/python_cson-1.0.9-py2.7.egg/cson.py", line 322, in cson2py
    return csons2py(''.join(infile.readlines()))
  File "/Library/Python/2.7/site-packages/python_cson-1.0.9-py2.7.egg/cson.py", line 318, in csons2py
    return json.loads(toJSON(csonString))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 22 (char 21)
```

Python 2.7.5 on OS X, using [these](https://github.com/idleberg/atom-icon-fonts/tree/master/snippets) CSON files.

**Comment by gt3389b** [comment]
The 'cson' you are referencing is the coffeescript version.  It seems some of the differences are subtle, but the main one seems to be that indentation matters (a hybrid of cson and yaml it appears) in coffeescript.
